apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-uygulamam
  labels:
    app: web-uygulamam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-uygulamam
  template:
    metadata:
      labels:
        app: web-uygulamam
    spec:
      containers:
      - name: web-uygulamam
        image: cab6y/web-uygulamam:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-uygulamam
spec:
  type: NodePort
  selector:
    app: web-uygulamam
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080