version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins-k8s-proje
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_TLS_CERTDIR=
      - KUBECONFIG=/var/jenkins_home/.kube/config
    volumes:
      - jenkins_home:/var/jenkins_home
      # Docker soket bağlantısı
      - /var/run/docker.sock:/var/run/docker.sock
      # Kubeconfig bağlantısı (Windows yolu)
      - C:/Users/CihanAbay/.kube:/var/jenkins_home/.kube:ro
      # Minikube sertifikaları (Windows yolu)
      - C:/Users/CihanAbay/.minikube:/var/jenkins_home/.minikube:ro
    restart: always

volumes:
  jenkins_home: